sfeir_school_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: dbt
      password: dbt
      port: 5432
      dbname: dbt
      schema: 'school'
      threads: 4
      connect_timeout: 10 # default 10 seconds
